# Generated by Django 5.2.3 on 2025-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_event_description_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
