# Generated by Django 5.2.3 on 2025-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_event_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
