# Generated by Django 5.2.3 on 2025-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_event_is_deleted_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
